apiVersion: apps/v1
kind: Deployment
metadata:
  name: hack-video-transcoder
  namespace: hack-video-transcoder
  labels:
    app: hack-video-transcoder
    tier: backend
  annotations:
    maintainer: "SOAT - Grupo 75"
    description: "Deployment do backend da aplicação Python"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hack-video-transcoder
  template:
    metadata:
      labels:
        app: hack-video-transcoder
    spec:
      containers:
        - name: hack-video-transcoder
          image: ${K8S_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          startupProbe:
            httpGet:
              path: /api/health
              port: 8080
            failureThreshold: 60
            timeoutSeconds: 5
            periodSeconds: 5
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
